name: Node.JS CI/CD

on:
  push:
    branches: [main]


jobs:
  # Tests & node-version
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout 
        uses: actions/checkout@v3 # last version was "v2"
        with: 
          fetch-depth: 0

      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3 # last version was "v2"
        with: 
          node-version: ${{ matrix.node-version }}

      # NPM install & build & test
      - name: NPM install, build and test
        run: |
          npm install
          npm run 
          npm test
        env: 
          DB_URL: ${{ secrets.DB_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}


  # deploy to render.com
  deploy:
    name: Deploy
    needs: [test] 
    runs-on: ubuntu-latest

    steps: 
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }} # Deploy Hook
          api-key: ${{ secrets.RENDER_API_KEY }} # Create API key in Render - Account Settings

    